# fly.toml app configuration file generated for Fly.io deployment
#
# Use 'fly launch' in your terminal to initialize your own unique app name.

app = "worldcup-predictions"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_rollback = true

[[mounts]]
  source = "predictions_data"
  destination = "/data"
  initial_size = "1gb"
